// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/underscore');
require('./vendor/ember');
require('./vendor/ember-data');
require('./vendor/ember-validations');
require('./vendor/ember-easyform');
require('./templates');
require('./functions');

var App = window.App = require('./app');

App.Store = require('./store');

App.SobreController = require('./controllers/sobre_controller');
App.AjusteRoute = require('./routes/ajuste_route');
App.SobreRoute = require('./routes/sobre_route');
App.AjusteView = require('./views/ajuste_view');
App.SobreView = require('./views/sobre_view');

require('./routes');

