// This file is auto-generated by `ember build`.
// You should not modify it.

window.addEventListener("load", function() {
  if (!!window.EventSource) {
    source = new EventSource("reload");
    source.addEventListener("message", function(event) {
      if(event.data == "true") location.reload();
    }, false);

    source.addEventListener("error", function(event) {
      if (event.target.readyState === EventSource.CLOSED) {
        console.log("Connection closed!");
      } else if (event.target.readyState === EventSource.CONNECTING) {
        console.log("Connection closed. Attempting to reconnect!");
      } else {
        console.log("Connection closed. Unknown error!");
      }
    }, false);

  } else {
    console.log("Sorry, your browser doesn't support server-sent events");
  }
}, false);
require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/underscore');
require('./vendor/ember');
require('./vendor/ember-data');
require('./vendor/ember-validations');
require('./vendor/ember-easyform');
require('./vendor/bootstrap');
require('./vendor/i18n');
require('./vendor/codemirror');
require('./vendor/xml');
require('./vendor/javascript');
require('./vendor/css');
require('./vendor/htmlmixed');
require('./templates');

require('./helpers/code_syntax');
require('./helpers/date_format');
require('./functions');

var App = window.App = require('./app');

App.Store = require('./config/store');

App.SobreController = require('./controllers/sobre_controller');
App.AjusteRoute = require('./routes/ajuste_route');
App.SobreRoute = require('./routes/sobre_route');
App.IndexBrowserEBuscadoresOQueVeemRoute = require('./routes/index/browser_e_buscadores_o_que_veem_route');
App.IndexGoogleEBingRoute = require('./routes/index/google_e_bing_route');
App.IndexIndexRoute = require('./routes/index/index_route');
App.AjaxBeneficiosRoute = require('./routes/ajax/beneficios_route');
App.AjaxComoFuncionaRoute = require('./routes/ajax/como_funciona_route');
App.AjaxMaleficiosRoute = require('./routes/ajax/maleficios_route');
App.AjaxOQueERoute = require('./routes/ajax/o_que_e_route');
App.AjusteView = require('./views/ajuste_view');
App.ApplicationView = require('./views/application_view');
App.CodeView = require('./views/code_view');
App.IndexView = require('./views/index_view');
App.SobreView = require('./views/sobre_view');
App.IndexBrowserEBuscadoresOQueVeemView = require('./views/index/browser_e_buscadores_o_que_veem_view');
App.IndexGoogleEBingView = require('./views/index/google_e_bing_view');
App.IndexIndexView = require('./views/index/index_view');
App.AjaxBeneficiosView = require('./views/ajax/beneficios_view');
App.AjaxComoFuncionaView = require('./views/ajax/como_funciona_view');
App.AjaxMaleficiosView = require('./views/ajax/maleficios_view');
App.AjaxOQueEView = require('./views/ajax/o_que_e_view');
require('./config/routes');
require('./config/locales');
